### ISSUE TITLE
App Responsiveness

### ISSUE THREAD

**Issue by JAYESH-555** [JAYESH-555/Quick-Shop-List-App#1]
Currently, the App is not responsive properly. More efficient responsive can be done.

**Comment by Almada2021** [comment]
@JAYESH-555  Hi I can help with responsive please assign me.

**Comment by JAYESH-555** [comment]
> @JAYESH-555 Hi I can help with responsive please assign me.

Please raise a PR for it I will check and assign accordingly.

Thanks.

**Comment by Almada2021** [comment]
ready https://github.com/JAYESH-555/Quick-Shop-List-App/pull/2 @JAYESH-555

**Comment by JAYESH-555** [comment]
> ready #2 @JAYESH-555

Thanks. I will review it once and let you know.

**Comment by JAYESH-555** [comment]
Updated the required CSS to make it responsive.
